base_config:
  file: .expeditor/base_config.yml


project:
  alias: expeditor-acceptance

pipelines:
  - new_cd_public:
      definition: .expeditor/new-cd-pipeline.pipeline.yml
      public: true
  - omnibus/harmony-acceptance:
      # do not use canary buildkite org to test omnibus pipelines because many platforms don't run canary buildkite agents
      env:
        - ADHOC: true
  - docker/build:
      canary: true
      env:
        - DOBI_S3_BUCKET_NAME: "docker-buildkite-cache-chef-canary-canary"
  - habitat/build:
      canary: true

merge_actions:
  - bash:.expeditor/create-another-pr.sh
  - create_github_issue:.expeditor/templates/pr_merge.mustache
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
  - trigger_pipeline:habitat/build
  - trigger_pipeline:docker/build
  - trigger_pipeline:omnibus/harmony-acceptance

subscriptions:
  - workload: generic_workload_published:acceptance_tests:*
    actions:
      - bash:.expeditor/trigger_pr_merge_tests.sh
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_docker_images
